# Generated by Django 3.2.4 on 2021-06-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=150, verbose_name='Брэнд')),
                ('car_model', models.CharField(max_length=100, verbose_name='Модель')),
                ('production_year', models.CharField(max_length=10, verbose_name='Год выпуска')),
                ('car_body', models.CharField(max_length=150, verbose_name='Кузов')),
                ('engine_type', models.CharField(max_length=50, verbose_name='Двигатель')),
            ],
        ),
    ]
