# Generated by Django 3.2.4 on 2021-07-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=120)),
                ('car_brand', models.CharField(max_length=100)),
                ('round_finish_time', models.IntegerField(default=0)),
            ],
        ),
    ]
